TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'Weissheiten.News': TRUE
    nodeTypes:
      groups:
        news:
          position: 280
          label: 'Weissheiten News'
Weissheiten:
  News:
    newsList:
      maxNumberOfItems: 10000
      pagination:
        itemsPerPage: 2
        maximumNumberOfLinks: 10
      sortProperty: created
    newsLatest:
      maxNumberOfItems: 5
      pagination: ~
      sortProperty: created


