TYPO3:
  Fluid:
    namespaces:
      'http://Weissheiten/Neos/News/ViewHelpers' : 'Weissheiten\Neos\News\ViewHelpers'
  Neos:
    typoScript:
      autoInclude:
        'Weissheiten.Neos.News': TRUE
    nodeTypes:
      groups:
        news:
          position: 280
          label: 'Weissheiten News'
Weissheiten:
  Neos:
    News:
      newsList:
        maxNumberOfItems: 10000
        pagination:
          itemsPerPage: 2
          maximumNumberOfLinks: 6
        sortProperty: creationDate
      newsLatest:
        maxNumberOfItems: 4
        pagination: ~
        sortProperty: creationDate
      eventList:
        maxNumberOfItems: 10000
        pagination:
          itemsPerPage: 20
          maximumNumberOfLinks: 6
        sortProperty: creationDate
      eventLatest:
        maxNumberOfItems: 10
        pagination: ~
        sortProperty: eventDate