
TYPO3:
  Fluid:
    namespaces:
      'http://Weissheiten/Neos/News/ViewHelpers': Weissheiten\Neos\News\ViewHelpers
Weissheiten:
  Neos:
    News:
      newsList:
        maxNumberOfItems: 10000
        pagination:
          itemsPerPage: 2
          maximumNumberOfLinks: 6
        sortProperty: sortDate
      newsLatest:
        maxNumberOfItems: 4
        pagination: null
        sortProperty: sortDate
      eventList:
        maxNumberOfItems: 10000
        pagination:
          itemsPerPage: 20
          maximumNumberOfLinks: 6
        sortProperty: sortDate
      eventLatest:
        maxNumberOfItems: 10
        pagination: null
        sortProperty: eventDate
Neos:
  Neos:
    nodeTypes:
      groups:
        news:
          position: 280
          label: 'Weissheiten News'
    fusion:
      autoInclude:
        Weissheiten.Neos.News: true
