TYPO3:
  Fluid:
    namespaces:
      'http://Weissheiten/News/ViewHelpers' : 'Weissheiten\News\ViewHelpers'
  Neos:
    typoScript:
      autoInclude:
        'Weissheiten.News': TRUE
    nodeTypes:
      groups:
        news:
          position: 280
          label: 'Weissheiten News'
Weissheiten:
  News:
    newsList:
      maxNumberOfItems: 10000
      pagination:
        itemsPerPage: 2
        maximumNumberOfLinks: 6
      sortProperty: creationDate
    newsLatest:
      maxNumberOfItems: 6
      tilingCols: 12
      pagination: ~
      sortProperty: creationDate
    eventList:
      maxNumberOfItems: 10000
      pagination:
        itemsPerPage: 20
        maximumNumberOfLinks: 6
      sortProperty: creationDate
    eventLatest:
      maxNumberOfItems: 6
      tilingCols: 12
      pagination: ~
      sortProperty: eventDate
